### ISSUE TITLE
Suggestion: Anyway to make the map less blurry when you zoom in?

### ISSUE THREAD

**Issue by FlameSlap** [lud99/totk-unexplored#6]
As the title mentions, when you zoom in the map it looks really blurry. Im on a 1080p TV and it still doesnt look good. Anyway we can add an image that has more resolution?

**Comment by lud99** [comment]
Hey! The reason is that homebrew in applet mode has very limited memory available to it, so if the map textures are any larger it wont work at all.
I’m sorry, but that’s how it is

**Comment by FlameSlap** [comment]
What about in title redirect where you get full access to the memory? Applet mode is limited so I can see how that would pose an issue. I also noticed that BOTW unexplored looks a lot better. I would guess it is becuase it is only one map/image. So my question is, is it possible we can get a title redirect version where the maps are a bit better and less eye straining?

**Comment by lud99** [comment]
Yes you are correct, title redirect supports higher map resolutions. The reason I didn’t add specific support for that was because I found having to close Zelda to use the homebrew was not very convenient, but it is not difficult for me to add it if you would find it useful :)

(And yes botw unexplored has higher resolution for the reason you thought. I tried to unload/load the textures when changing layers but it would stutter so I decided against it)

I will try to release an updated version for title override as soon as possible!

**Comment by FlameSlap** [comment]
NIICE!! :D THANK! Here are the maps updated to higher resolutions too if it helps. :)

https://ibb.co/LPgB1TX
https://ibb.co/gSjxR8j
https://ibb.co/F77NcF3

I upscaled them to 3000x3000 but you can make them smaller of course.

**Comment by lud99** [comment]
Cool! I am curious, where did you find the higher resolution images?

**Comment by FlameSlap** [comment]
I used [pixel cut](https://www.pixelcut.ai/image-upscaler). It's an online tool for image manipulation. One of them being image upscaling. It works pretty well in my opinion.

**Comment by lud99** [comment]
There is an updated version available for download now :)

**Comment by FlameSlap** [comment]
> There is an updated version available for download now :)

Niiiiice!! Thanks for all the hard work bud!! 🙏🏻🙏🏻🙏🏻😃😃😃
